version: "3"
services:
  db:
    image: mdillon/postgis:9.6-alpine
    environment:
      POSTGRES_PASSWORD: abcde
      POSTGRES_USER: kaguyamgr
      POSTGRES_DB: kaguyasp
    volumes:
      - "/var/lib/dockervols/kaguya/postgresql:/var/lib/postgresql/data"
    ports:
        - "9009:5432"
  admin:
      image: jlaura/pgadmin4:0.2
      ports:
      - "9092:5050"
